//go:build !ignore_autogenerated

/*
Copyright 2025 Mateusz Woźniak <wozniakmat@student.agh.edu.pl>.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinConformationPrediction) DeepCopyInto(out *ProteinConformationPrediction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinConformationPrediction.
func (in *ProteinConformationPrediction) DeepCopy() *ProteinConformationPrediction {
	if in == nil {
		return nil
	}
	out := new(ProteinConformationPrediction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProteinConformationPrediction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinConformationPredictionList) DeepCopyInto(out *ProteinConformationPredictionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProteinConformationPrediction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinConformationPredictionList.
func (in *ProteinConformationPredictionList) DeepCopy() *ProteinConformationPredictionList {
	if in == nil {
		return nil
	}
	out := new(ProteinConformationPredictionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProteinConformationPredictionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinConformationPredictionSpec) DeepCopyInto(out *ProteinConformationPredictionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinConformationPredictionSpec.
func (in *ProteinConformationPredictionSpec) DeepCopy() *ProteinConformationPredictionSpec {
	if in == nil {
		return nil
	}
	out := new(ProteinConformationPredictionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinConformationPredictionStatus) DeepCopyInto(out *ProteinConformationPredictionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinConformationPredictionStatus.
func (in *ProteinConformationPredictionStatus) DeepCopy() *ProteinConformationPredictionStatus {
	if in == nil {
		return nil
	}
	out := new(ProteinConformationPredictionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinDatabase) DeepCopyInto(out *ProteinDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinDatabase.
func (in *ProteinDatabase) DeepCopy() *ProteinDatabase {
	if in == nil {
		return nil
	}
	out := new(ProteinDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProteinDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinDatabaseDatasetDownloadProgress) DeepCopyInto(out *ProteinDatabaseDatasetDownloadProgress) {
	*out = *in
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.DeltaDuration != nil {
		in, out := &in.DeltaDuration, &out.DeltaDuration
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinDatabaseDatasetDownloadProgress.
func (in *ProteinDatabaseDatasetDownloadProgress) DeepCopy() *ProteinDatabaseDatasetDownloadProgress {
	if in == nil {
		return nil
	}
	out := new(ProteinDatabaseDatasetDownloadProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinDatabaseDatasetDownloadStatus) DeepCopyInto(out *ProteinDatabaseDatasetDownloadStatus) {
	*out = *in
	in.MGYClusters.DeepCopyInto(&out.MGYClusters)
	in.BFD.DeepCopyInto(&out.BFD)
	in.UniRef90.DeepCopyInto(&out.UniRef90)
	in.UniProt.DeepCopyInto(&out.UniProt)
	in.PDB.DeepCopyInto(&out.PDB)
	in.PDBSeqReq.DeepCopyInto(&out.PDBSeqReq)
	in.RNACentral.DeepCopyInto(&out.RNACentral)
	in.NT.DeepCopyInto(&out.NT)
	in.RFam.DeepCopyInto(&out.RFam)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinDatabaseDatasetDownloadStatus.
func (in *ProteinDatabaseDatasetDownloadStatus) DeepCopy() *ProteinDatabaseDatasetDownloadStatus {
	if in == nil {
		return nil
	}
	out := new(ProteinDatabaseDatasetDownloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinDatabaseDatasetSelection) DeepCopyInto(out *ProteinDatabaseDatasetSelection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinDatabaseDatasetSelection.
func (in *ProteinDatabaseDatasetSelection) DeepCopy() *ProteinDatabaseDatasetSelection {
	if in == nil {
		return nil
	}
	out := new(ProteinDatabaseDatasetSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinDatabaseList) DeepCopyInto(out *ProteinDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProteinDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinDatabaseList.
func (in *ProteinDatabaseList) DeepCopy() *ProteinDatabaseList {
	if in == nil {
		return nil
	}
	out := new(ProteinDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProteinDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinDatabaseSpec) DeepCopyInto(out *ProteinDatabaseSpec) {
	*out = *in
	out.Datasets = in.Datasets
	in.Volume.DeepCopyInto(&out.Volume)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinDatabaseSpec.
func (in *ProteinDatabaseSpec) DeepCopy() *ProteinDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(ProteinDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinDatabaseStatus) DeepCopyInto(out *ProteinDatabaseStatus) {
	*out = *in
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	in.Datasets.DeepCopyInto(&out.Datasets)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinDatabaseStatus.
func (in *ProteinDatabaseStatus) DeepCopy() *ProteinDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(ProteinDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProteinDatabaseVolume) DeepCopyInto(out *ProteinDatabaseVolume) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProteinDatabaseVolume.
func (in *ProteinDatabaseVolume) DeepCopy() *ProteinDatabaseVolume {
	if in == nil {
		return nil
	}
	out := new(ProteinDatabaseVolume)
	in.DeepCopyInto(out)
	return out
}
