---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.kubefold.io
  resources:
  - proteinconformationpredictions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.kubefold.io
  resources:
  - proteinconformationpredictions/finalizers
  verbs:
  - update
- apiGroups:
  - data.kubefold.io
  resources:
  - proteinconformationpredictions/status
  verbs:
  - get
  - patch
  - update
