apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: alphafold-cluster
  region: eu-central-1
nodeGroups:
  - name: ng-primary
    instanceType: t3.medium
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: fsx-csi-controller-sa
        namespace: kube-system
        labels: { aws-usage: "application" }
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AmazonFSxFullAccess"

vpc:
  id: vpc-0ade33da149682ec2
  subnets:
    private:
      eu-central-1a:
        id: "subnet-0b65addd5a2ceb7ff"
      eu-central-1b:
        id: "subnet-0c7068ea9c3422130"
    public:
      eu-central-1a:
        id: "subnet-038b10f6f4ac5aacd"
      eu-central-1b:
        id: "subnet-099b2b55ca156bb7d"

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: eks-pod-identity-agent