apiVersion: data.kubefold.io/v1
kind: ProteinConformationPrediction
metadata:
  labels:
    app.kubernetes.io/name: kubefold
    app.kubernetes.io/managed-by: kustomize
  name: proteinconformationprediction-sample
spec:
  job:
    searchNodeSelector:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
                - m5.xlarge
    predictionNodeSelector:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
                - g5.xlarge
  database: proteindatabase-sample
  backend:
    image: registry.example.com/alphafold2:latest
  protein:
    id: [ 'A','B' ]
    sequence: GMRESYANENQFGFKTINSDIHKIVIVGGYGKLGGLFARYLRASGYPISILDREDWAVAESILANADVVIVSVPINLTLETIERLKPYLTENMLLADLTSVKREPLAKMLEVHTGAVLGLHPMFGADIASMAKQVVVRCDGRFPERYEWLLEQIQIWGAKIYQTNATEHDHNMTYIQALRHFSTFANGLHLSKQPINLANLLALSSPIYRLELAMIGRLFAQDAELYADIIMDKSENLAVIETLKQTYDEALTFFENNDRQGFIDAFHKVRDWFGDYSEQFLKESRQLLQQANDLKQG
  model:
    volume:
      storageClassName: fsx-sc
    weights:
      http: https://example.org/af2-model-parameters.tar
    seeds:
      - 1
  destination:
    s3:
      bucket: kubefold-artifacts-example
      region: eu-central-1
  notify:
    region: eu-central-1
    sms:
      - "+48123456789"
