apiVersion: data.kubefold.io/v1
kind: ProteinConformationPrediction
metadata:
  labels:
    app.kubernetes.io/name: kubefold
    app.kubernetes.io/managed-by: kustomize
  name: proteinconformationprediction-sample
spec:
  database: proteindatabase-sample
  protein:
    sequence: GMRESYANENQFGFKTINSDIHKIVIVGGYGKLGGLFARYLRASGYPISILDREDWAVAESILANADVVIVSVPINLTLETIERLKPYLTENMLLADLTSVKREPLAKMLEVHTGAVLGLHPMFGADIASMAKQVVVRCDGRFPERYEWLLEQIQIWGAKIYQTNATEHDHNMTYIQALRHFSTFANGLHLSKQPINLANLLALSSPIYRLELAMIGRLFAQDAELYADIIMDKSENLAVIETLKQTYDEALTFFENNDRQGFIDAFHKVRDWFGDYSEQFLKESRQLLQQANDLKQG
  model:
    seeds:
      - 1
  destination:
    s3: s3://kubefold-artifacts-sample/out
  notify:
    sms:
      - "505506682"
